### ISSUE TITLE
Improve requirements search and filter.

### ISSUE THREAD

**Issue by samurous** [ultimate-pa/hanfor#28]
# Todo
* [x] Apply search only on visible columns.
* [x] Implement exact word match:
  * `"string"` only matches `string` (`r"\bstring\b"`)
* [x] Implement negation:
  * `:NOT:<string>` removes all matches of `<string>`
  * `:NOT:"<string>"` removes all exact matches of string
* [x] Concatination
  * [x] `<search_1> :OR: <search_2>` (result is union of the result for `<search_1>`, `<search_2>`)
  * [x] `<search_2> :AND: <search_2>` (apply `<search_2>` to the result for `<search_1>`)
* [x] Filter
  * [x] Support `:AND:` and `:OR:`
  * [x] Suport `:NOT:`
